-- CREATE DATABASE NHL_Database
-- Go

/*
CREATE TABLE dbo.Players (
    PlayerID BIGINT PRIMARY KEY,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    Status NVARCHAR(50),
    TeamID INT,
    Team NVARCHAR(10),
    Position NVARCHAR(10),
    Jersey NVARCHAR(10) NULL,
    Catches NVARCHAR(1) NULL,
    Shoots NVARCHAR(1) NULL,
    Height INT,
    Weight INT,
    BirthDate DATE,
    BirthCity NVARCHAR(100),
    BirthState NVARCHAR(50),
    PhotoUrl NVARCHAR(500),
    InjuryStatus NVARCHAR(50),
    FanDuelPlayerID INT,
    DraftKingsPlayerID INT,
    FanDuelName NVARCHAR(100),
    DraftKingsName NVARCHAR(100)
);
*/

ALTER TABLE Players
ALTER COLUMN FirstName NVARCHAR(50)

ALTER TABLE Players
ALTER COLUMN LastName NVARCHAR(50)

ALTER TABLE Players
ALTER COLUMN Status NVARCHAR(50)

ALTER TABLE Players
ALTER COLUMN Team NVARCHAR(10)

ALTER TABLE Players
ALTER COLUMN Position NVARCHAR(10)

ALTER TABLE Players
ALTER COLUMN Jersey NVARCHAR(50)

ALTER TABLE Players
ALTER COLUMN Catches NVARCHAR(1)

ALTER TABLE Players
ALTER COLUMN Shoots NVARCHAR(1)

ALTER TABLE Players
ALTER COLUMN BirthCity NVARCHAR(50)

ALTER TABLE Players
ALTER COLUMN BirthState NVARCHAR(50)

ALTER TABLE Players
ALTER COLUMN PhotoUrl NVARCHAR(250)

ALTER TABLE Players
ALTER COLUMN InjuryStatus NVARCHAR(50)

ALTER TABLE Players
ALTER COLUMN FanDuelName NVARCHAR(50)

ALTER TABLE Players
ALTER COLUMN DraftKingsName NVARCHAR(50)


-- Early rounds to get the table to match the ssis layout

/*
ALTER TABLE Players
ALTER COLUMN Team NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Position NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Catches NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Shoots NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Team NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Position NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Catches NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Shoots NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Team NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Position NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Catches NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Shoots NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN FirstName NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN LastName NVARCHAR(50);

ALTER TABLE Players
ALTER COLUMN Status NVARCHAR(50);
*/